version: 3

env:
  PATH_SCRIPT: script/main/main.go
  PATH_MAIN: cmd/main/main.go
  PATH_DEV_CFG: config/dev.yaml
  PATH_PROD_CFG: config/prod.yaml
  PATH_LOCAL_CFG: config/local.yaml
  PATH_TEST_CFG: config/test.yaml

  PATH_MIGRATION_PSQL_DIR: migration/psql

  PROTO_SRC: 'proto'
  PROTO_FILES: 'proto/*.proto'
  PROTO_FILES_IN: 'proto/google/**/*.proto'
  PROTO_OUT: './protogen/'

tasks:
  proto:
    cmds:
      - protoc -I $PROTO_SRC $PROTO_FILES --go_out=$PROTO_OUT --go_opt=paths=source_relative --go-grpc_out=$PROTO_OUT --go-grpc_opt=paths=source_relative --grpc-gateway_opt=paths=source_relative --grpc-gateway_out=$PROTO_OUT --grpc-gateway_opt=generate_unbound_methods=true
#      - protoc -I $PROTO_SRC $PROTO_FILES_IN --go_out=$PROTO_OUT --go_opt=paths=source_relative --go-grpc_out=$PROTO_OUT --go-grpc_opt=paths=source_relative